linters:
  disable:
    - unused
  enable:
    - gci
    - gofmt
    - gosimple
    - misspell
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/safchain/ethtool)
