linters:
  enable:
    - gci
    - gofmt
    - gosimple
    - misspell
    - unused
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/safchain/ethtool)
