name: "Unit tests"
run-name: ${{ github.actor }} is testing ethtool 🚀
on: [push, pull_request]
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Run unit tests
        run: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
